"""add more indexes and audit table

Revision ID: 5ec59540ad4f
Revises: a2cf2e710bb8
Create Date: 2026-03-02 13:00:02.074169

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect

# revision identifiers, used by Alembic.
revision: str = '5ec59540ad4f'
down_revision: Union[str, None] = 'a2cf2e710bb8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    bind = op.get_bind()
    inspector = inspect(bind)
    existing_tables = inspector.get_table_names()

    # ### commands auto generated by Alembic - please adjust! ###
    if 'audit_log' in existing_tables:
        print("Table 'audit_log' already exists, skipping creation.")
        return
    
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('level', sa.String(length=8), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('resource_type', sa.String(length=32), nullable=True),
    sa.Column('resource_id', sa.String(length=128), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_log_action', 'audit_log', ['action'], unique=False)
    op.create_index('ix_audit_log_timestamp', 'audit_log', ['timestamp'], unique=False)
    op.create_index('ix_audit_log_user_id', 'audit_log', ['user_id'], unique=False)
    op.create_index('ix_bought_goods_buyer_datetime', 'bought_goods', ['buyer_id', 'bought_datetime'], unique=False)
    op.create_index('ix_bought_goods_datetime', 'bought_goods', ['bought_datetime'], unique=False)
    op.alter_column('operations', 'user_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.create_index('ix_operations_time', 'operations', ['operation_time'], unique=False)
    op.drop_constraint(op.f('operations_user_id_fkey'), 'operations', type_='foreignkey')
    op.create_foreign_key(None, 'operations', 'users', ['user_id'], ['telegram_id'], ondelete='SET NULL')
    op.alter_column('payments', 'user_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.create_index('ix_payments_status_created', 'payments', ['status', 'created_at'], unique=False)
    op.drop_constraint(op.f('payments_user_id_fkey'), 'payments', type_='foreignkey')
    op.create_foreign_key(None, 'payments', 'users', ['user_id'], ['telegram_id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.create_foreign_key(op.f('payments_user_id_fkey'), 'payments', 'users', ['user_id'], ['telegram_id'], ondelete='CASCADE')
    op.drop_index('ix_payments_status_created', table_name='payments')
    op.alter_column('payments', 'user_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.drop_constraint(None, 'operations', type_='foreignkey')
    op.create_foreign_key(op.f('operations_user_id_fkey'), 'operations', 'users', ['user_id'], ['telegram_id'], ondelete='CASCADE')
    op.drop_index('ix_operations_time', table_name='operations')
    op.alter_column('operations', 'user_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.drop_index('ix_bought_goods_datetime', table_name='bought_goods')
    op.drop_index('ix_bought_goods_buyer_datetime', table_name='bought_goods')
    op.drop_index('ix_audit_log_user_id', table_name='audit_log')
    op.drop_index('ix_audit_log_timestamp', table_name='audit_log')
    op.drop_index('ix_audit_log_action', table_name='audit_log')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
