"""add_ban_option

Revision ID: a2cf2e710bb8
Revises: 5de189770cf2
Create Date: 2025-12-18 13:57:33.555108

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision: str = 'a2cf2e710bb8'
down_revision: Union[str, None] = '5de189770cf2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    bind = op.get_bind()
    inspector = inspect(bind)
    columns = [col['name'] for col in inspector.get_columns('users')]

    op.drop_index(op.f('ix_bought_goods_buyer_time'), table_name='bought_goods')
    op.drop_index(op.f('ix_operations_user_time'), table_name='operations')

    if 'is_blocked' not in columns:
        op.add_column('users', sa.Column('is_blocked', sa.Boolean(), nullable=True))
        op.create_index(op.f('ix_users_is_blocked'), 'users', ['is_blocked'], unique=False)
    else:
        print("Column 'is_blocked' already exists in 'users', skipping.")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_is_blocked'), table_name='users')
    op.drop_column('users', 'is_blocked')
    op.create_index(op.f('ix_operations_user_time'), 'operations', ['user_id', sa.literal_column('operation_time DESC')], unique=False)
    op.create_index(op.f('ix_bought_goods_buyer_time'), 'bought_goods', ['buyer_id', sa.literal_column('bought_datetime DESC')], unique=False)
    # ### end Alembic commands ###
